In [52]:
docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [53]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [54]:
tokenizer.fit_on_texts(docs)

In [55]:
len(tokenizer.word_index)

17

In [56]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [57]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]])

In [58]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

model = Sequential()
model.add(Embedding(17,output_dim=2,input_length=5))


In [59]:
model.compile('adam','accuracy')

In [60]:
import numpy as np
sequences = np.clip(sequences, 0, 16)

pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 258ms/step
[[[-4.5054961e-02 -1.0500956e-02]
  [ 2.0313989e-02  2.8030168e-02]
  [-4.7976412e-02  2.7024936e-02]
  [-4.7976412e-02  2.7024936e-02]
  [-4.7976412e-02  2.7024936e-02]]

 [[ 2.0313989e-02  2.8030168e-02]
  [ 2.0313989e-02  2.8030168e-02]
  [-4.7976412e-02  2.7024936e-02]
  [-4.7976412e-02  2.7024936e-02]
  [-4.7976412e-02  2.7024936e-02]]

 [[-1.0020815e-02  4.9957875e-02]
  [-1.0020815e-02  4.9957875e-02]
  [ 2.0175967e-02  3.4731094e-02]
  [-4.7976412e-02  2.7024936e-02]
  [-4.7976412e-02  2.7024936e-02]]

 [[-1.1364259e-02  3.7252579e-02]
  [-2.0971075e-03 -3.4051098e-02]
  [-1.1364259e-02  3.7252579e-02]
  [ 2.0313989e-02  2.8030168e-02]
  [-1.1364259e-02  3.7252579e-02]]

 [[ 4.2195503e-02  7.1514398e-05]
  [ 4.9048316e-02 -4.9979210e-02]
  [-2.4830092e-02  5.4940954e-03]
  [ 1.6959395e-02  3.5484675e-02]
  [-4.7976412e-02  2.7024936e-02]]

 [[ 1.3935234e-02 -3.3022001e-02]
  [ 1.3935234e-02 -3.3022001e-02]
  [-4.7976412e-02  2.7024936e-02]

In [61]:
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [62]:
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=10000)

In [63]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [64]:
X_train.shape

(25000, 50)

In [65]:
model = Sequential()
model.add(Embedding(input_dim=10000, output_dim=2, input_length=50))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1, activation='sigmoid'))



In [66]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 20s 20ms/step - acc: 0.5228 - loss: 0.6916 - val_acc: 0.7168 - val_loss: 0.5660
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 15s 19ms/step - acc: 0.7599 - loss: 0.4963 - val_acc: 0.8071 - val_loss: 0.4270
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 16s 20ms/step - acc: 0.8570 - loss: 0.3398 - val_acc: 0.8075 - val_loss: 0.4306
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 15s 20ms/step - acc: 0.8810 - loss: 0.2941 - val_acc: 0.8048 - val_loss: 0.4569
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 15s 20ms/step - acc: 0.8994 - loss: 0.2577 - val_acc: 0.7878 - val_loss: 0.5703


In [67]:
# Get the word index used by the IMDB dataset
word_index = imdb.get_word_index()

# Adjust indices (Keras reserves 0-3)
word_index = {k: (v + 3) for k, v in word_index.items()}
word_index["<PAD>"] = 0
word_index["<START>"] = 1
word_index["<UNK>"] = 2
word_index["<UNUSED>"] = 3

In [68]:
def simple_encode(text): 
    words = text.lower().split()
    encoded = [1]  # Start token
    for word in words:
        encoded.append(word_index.get(word, 2))  # Unknown if not found
    return pad_sequences([encoded], maxlen=50, padding='post')

In [75]:
# Your custom sentence
text = "the movie was  bad"

# Encode and predict
encoded = simple_encode(text)
pred = model.predict(encoded)

print("Sentiment score:", pred[0][0])
print("Prediction:", "Positive 😊" if pred[0][0] >= 0.5 else "Negative 😞")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step
Sentiment score: 0.29067
Prediction: Negative 😞
